{
 "title": "SafeSquid - Configuration Portal Reports",
 "description": "Confirmation Portal Logs provide a detailed record of user authentication attempts to SafeSquid's web interface, access verifications, and configuration updates. These logs help track user activity, detect anomalies, and ensure security compliance. Ideal for monitoring updates overtime for your policy management. ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\":\"hostname\" }"
   },
   {
    "name": "server_ip",
    "label": "Server IP",
    "query": "{\"find\": \"terms\", \"field\":\"server_ip\" }"
   }
  ]
 },
 "panels": [
  {
   "title": "Policy Creation",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "section",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "F0",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "F1",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "subsection",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action: \"add\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Configuration File Uploaded",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "overwrite",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "type",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "username",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "handler: \"upload\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Configuration File Downloaded",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filename",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "username",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT filename: \"-\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Interface Accessed User and IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "safesquid_interface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}