{
 "title": "SafeSquid - CSP Reports",
 "description": "Content Security Policy Reports provides detailed insights into CSP violations, helping identify blocked resources, potential security risks, and policy misconfigurations. This dashboard is essential for monitoring and improving web application security by analyzing real-time CSP reports.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\":\"hostname\",\"size\": \"1000000\" }"
   },
   {
    "name": "server_ip",
    "label": "Server IP",
    "query": "{\"find\": \"terms\", \"field\":\"server_ip\",\"size\": \"1000000\" }"
   }
  ]
 },
 "panels": [
  {
   "title": "Violated Directives",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violated_directive",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User-Based CSP Violations",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "No. of Blocked Requets",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violated_directive",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "document_uri",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "blocked_uri",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CSP Policy Enforced",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "original_policy",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CSP Blocked URI (Overview)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "document_uri",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "source-file",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "blocked_uri",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "violated_directive",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "original_policy",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Blocked iframe Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violated_directive",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "blocked_uri",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "document_uri",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "violated_directive: ( \"frame-src\" OR  \"frame-ancestors\" OR \"child-src\" ) AND disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Blocked Cross Doamin Connections (XHR)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violated_directive",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "document_uri",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "blocked_uri",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "violated_directive: \"connect-src\" AND disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Possible Prevention for Form Hijacking",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violated_directive",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "user",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "blocked_uri",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "violated_directive: \"form-action\" AND disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Prevention for Mixed Content Attacks",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violated_directive",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "blocked_uri",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "Violated_directive: \"block-all-mixed-content\" AND disposition: \"enforce\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Report Only Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "CSP Report Only (Overview)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "document_uri",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "source-file",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "blocked_uri",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "violated_directive",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "original_policy",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "disposition: \"report\" AND hostname: $hostname AND server_ip: $server_ip",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}