{
 "title": "User Reports",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "{\"find\": \"terms\", \"field\":\"username\",\"size\": \"1000000\" }"
   },
   {
    "name": "req_host",
    "label": "Destination",
    "query": "{\"find\": \"terms\", \"field\":\"request_host\",\"size\": \"1000000\" }"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\":\"hostname\",\"size\": \"1000000\" }"
   },
   {
    "name": "server_ip",
    "label": "Server IP",
    "query": "{\"find\": \"terms\", \"field\":\"server_ip\",\"size\": \"1000000\" }"
   }
  ]
 },
 "panels": [
  { "title": "General Usage Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top User",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "username:$user AND NOT cachecode: (\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\") AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top User Groups",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_groups",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Site",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode: (\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\") AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application List",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "application_signatures",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Endpoint Applications",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "useragent",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User Access",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "client_ip",
       "id": "14",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "username",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "request_host",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "method: ( \"CONNECT\" OR \"GET\" OR \"POST\" ) AND NOT cachecode: (\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\" ) AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User Total Usage Time ",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "request_host",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "elapsed_time", "id": "1", "type": "sum" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Downloads",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "download_content_types",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "download", "id": "13", "type": "sum" }
     ],
     "query": "method: \"GET\" AND NOT cachecode: (\"TCP_DENIED\" OR  \"TCP_SSL_HANDSHAKE\" ) AND NOT download_content_types: \"-\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Uploads",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "upload_content_types",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "request_host",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "download", "id": "1", "type": "sum" }
     ],
     "query": "method: \"POST\" AND NOT cachecode: (\"TCP_DENIED\" OR  \"TCP_SSL_HANDSHAKE\" ) AND NOT upload_content_types: \"-\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "download",
       "hide": false,
       "id": "3",
       "type": "sum"
      },
      { "field": "upload", "id": "4", "type": "sum" }
     ],
     "query": "username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Categories",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "categories",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hits of users",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "username",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode:(\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\" ) AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traffic by User",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "download",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "NOT cachecode: (\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\" )  AND method: ( \"CONNECT\" OR \"GET\" OR \"POST\") AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode: ( \"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\" ) AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Blocked Destinations ",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "username",
       "id": "6",
       "settings": {
        "min_doc_count": "1",
        "missing": "anonyms",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "status: 451 AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Geo Destination",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "peer",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT peer: \"-\" AND (method:CONNECT OR method:GET OR method:POST) AND NOT cachdecode:\"TCP_DENIED\" AND username:$user AND requested_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TCP Status Code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cachecode",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Host and its Referers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "http_referer",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT http_referer: \"-\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "User Threat Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Top Blocked Categories",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "categories",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "status: ( 451 or 453 ) AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threat Prevented By",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "categories",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "filter_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "filtering_reason",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "categories:( \"Anonymizers\" OR \n           \"Botnets\" OR \n           \"Compromised\" OR \n           \"Hacking\" OR \n           \"Illegal Software\" OR \n           \"Malware\" OR \n           \"Peer-to-Peer\" OR \n           \"Phishing & Fraud\" OR \n           \"Spam Sites\" OR \n           \"Alcohol & Tobacco\" OR \n           \"Criminal Activity\" OR \n           \"Cults\" OR \n           \"Gambling\" OR \n           \"Hate & Intolerance\" OR \n           \"Illegal Drug\" OR \n           \"School Cheating\" OR \n           \"Tasteless\" OR \n           \"Unknown\" OR \n           \"Violence\" ) AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Malware Downloads",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "filtering_reason",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "filter_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "request_host",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: 453 AND method: \"GET\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Malware Uploads",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_groups",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "filtering_reason",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "filter_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "request_host",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: 453 AND method: \"POST\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threatful Categories and Host",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "categories",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "request_host",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "categories:( \"Anonymizers\" OR \n           \"Botnets\" OR \n           \"Compromised\" OR \n           \"Hacking\" OR \n           \"Illegal Software\" OR \n           \"Malware\" OR \n           \"Peer-to-Peer\" OR \n           \"Phishing & Fraud\" OR \n           \"Spam Sites\" OR \n           \"Alcohol & Tobacco\" OR \n           \"Criminal Activity\" OR \n           \"Cults\" OR \n           \"Gambling\" OR \n           \"Hate & Intolerance\" OR \n           \"Illegal Drug\" OR \n           \"School Cheating\" OR \n           \"Tasteless\" OR \n           \"Unknown\" OR  \n           \"Violence\" ) AND NOT cachecode: \"TCP_SSL_HANDSHAKE\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hosts with SSL Inspection Bypassed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "cachecode: \"TCP_TUNNEL\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threatful User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "categories",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "username",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "client_ip",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "categories:( \"Anonymizers\" OR \n           \"Botnets\" OR \n           \"Compromised\" OR \n           \"Hacking\" OR \n           \"Illegal Software\" OR \n           \"Malware\" OR \n           \"Peer-to-Peer\" OR \n           \"Phishing & Fraud\" OR \n           \"Spam Sites\" OR \n           \"Alcohol & Tobacco\" OR \n           \"Criminal Activity\" OR \n           \"Cults\" OR \n           \"Gambling\" OR \n           \"Hate & Intolerance\" OR \n           \"Illegal Drug\" OR \n           \"School Cheating\" OR \n           \"Tasteless\" OR \n           \"Unknown\" OR \n           \"Violence\" ) AND NOT cachecode: \"TCP_SSL_HANDSHAKE\" AND username:$user AND request_host:$req_host AND hostname:$hostname AND server_ip:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}